name: gestao_ordem_servico_docker

services:
  postgres:
    image: postgres:16
    container_name: gestao_ordem_servico_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_ordem_servico
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: gos-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: gestao_ordem_servico
      NODE_ENV: production

volumes:
  postgres_data:

